# Generated by Django 5.2.13 on 2026-04-11 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_timestamp', models.DateTimeField(auto_now_add=True)),
                ('meralco_account_number', models.CharField(max_length=100)),
                ('billing_period', models.CharField(max_length=100)),
                ('total_kwh_consumed', models.FloatField()),
                ('total_bill_php', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
