# Generated by Django 5.2.13 on 2026-04-11 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(max_length=100)),
                ('expected_wattage_range', models.CharField(max_length=100)),
                ('actual_wattage', models.FloatField()),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
