# Generated by Django 5.2.13 on 2026-05-26 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_monitoring', '0003_advanced_db_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=100, unique=True)),
                ('device_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('alert_type', models.CharField(choices=[('HIGH_USAGE_ANOMALY', 'High Usage Anomaly'), ('UNUSUAL_PATTERN', 'Unusual Pattern'), ('DEVICE_MALFUNCTION', 'Device Malfunction'), ('BILLING_DISCREPANCY', 'Billing Discrepancy')], max_length=50)),
                ('expected_wattage_range', models.CharField(max_length=50)),
                ('actual_wattage', models.FloatField()),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
