# Generated by Django 5.2.13 on 2026-05-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='meralco_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
